services:
  ml_dev:
    build: .
    volumes:
      - $PWD:/work
    working_dir: /work
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
